const competitions = [
  {
    id: 2006,
    area: {
      id: 2001,
      name: 'Africa',
      countryCode: 'AFR',
      ensignUrl: null,
    },
    name: 'WC Qualification CAF',
    code: 'QCAF',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1609,
      startDate: '2023-11-15',
      endDate: '2025-10-13',
      currentMatchday: 5,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2022-03-13T18:51:44Z',
  },
  {
    id: 2176,
    area: {
      id: 2001,
      name: 'Africa',
      countryCode: 'AFR',
      ensignUrl: null,
    },
    name: 'Africa Cup',
    code: 'AC',
    emblemUrl: 'https://crests.football-data.org/ac.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1637,
      startDate: '2024-01-13',
      endDate: '2024-01-24',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-01-13T11:34:43Z',
  },
  {
    id: 2166,
    area: {
      id: 2001,
      name: 'Africa',
      countryCode: 'AFR',
      ensignUrl: null,
    },
    name: 'AFC Champions League',
    code: 'ACL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1559,
      startDate: '2022-04-06',
      endDate: '2023-05-05',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2023-02-26T12:57:33Z',
  },
  {
    id: 2023,
    area: {
      id: 2011,
      name: 'Argentina',
      countryCode: 'ARG',
      ensignUrl: 'https://crests.football-data.org/762.png',
    },
    name: 'Primera B Nacional',
    code: 'PBN',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 716,
      startDate: '2021-03-13',
      endDate: '2021-12-26',
      currentMatchday: 17,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2023-08-01T08:40:24Z',
  },
  {
    id: 2024,
    area: {
      id: 2011,
      name: 'Argentina',
      countryCode: 'ARG',
      ensignUrl: 'https://crests.football-data.org/762.png',
    },
    name: 'Liga Profesional',
    code: 'ASL',
    emblemUrl: 'https://crests.football-data.org/LPDF.svg',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 2262,
      startDate: '2024-05-12',
      endDate: '2024-12-15',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-05-28T18:02:40Z',
  },
  {
    id: 2149,
    area: {
      id: 2011,
      name: 'Argentina',
      countryCode: 'ARG',
      ensignUrl: 'https://crests.football-data.org/762.png',
    },
    name: 'Copa Liga Profesional',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 717,
      startDate: '2021-02-12',
      endDate: '2021-05-30',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2024-06-20T18:58:13Z',
  },
  {
    id: 2025,
    area: {
      id: 2011,
      name: 'Argentina',
      countryCode: 'ARG',
      ensignUrl: 'https://crests.football-data.org/762.png',
    },
    name: 'Supercopa Argentina',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 430,
      startDate: '2019-04-04',
      endDate: '2019-04-04',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2019-05-03T05:08:18Z',
  },
  {
    id: 2147,
    area: {
      id: 2014,
      name: 'Asia',
      countryCode: 'ASI',
      ensignUrl: null,
    },
    name: 'WC Qualification AFC',
    code: 'QAFC',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1616,
      startDate: '2023-10-12',
      endDate: '2024-06-11',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-11-11T10:31:11Z',
  },
  {
    id: 2008,
    area: {
      id: 2015,
      name: 'Australia',
      countryCode: 'AUS',
      ensignUrl: null,
    },
    name: 'A League',
    code: 'AAL',
    emblemUrl: 'https://crests.football-data.org/a-league.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 1628,
      startDate: '2023-10-20',
      endDate: '2024-05-25',
      currentMatchday: 27,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-01-13T10:56:25Z',
  },
  {
    id: 2026,
    area: {
      id: 2015,
      name: 'Australia',
      countryCode: 'AUS',
      ensignUrl: null,
    },
    name: 'FFA Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 592,
      startDate: '2020-02-19',
      endDate: '2020-10-28',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-10-23T23:59:22Z',
  },
  {
    id: 2020,
    area: {
      id: 2016,
      name: 'Austria',
      countryCode: 'AUT',
      ensignUrl: 'https://crests.football-data.org/816.svg',
    },
    name: 'Erste Liga',
    code: 'AEL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1626,
      startDate: '2023-07-28',
      endDate: '2024-05-26',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2023-08-22T20:41:17Z',
  },
  {
    id: 2012,
    area: {
      id: 2016,
      name: 'Austria',
      countryCode: 'AUT',
      ensignUrl: 'https://crests.football-data.org/816.svg',
    },
    name: 'Bundesliga',
    code: 'ABL',
    emblemUrl: 'https://crests.football-data.org/abl.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1588,
      startDate: '2023-07-28',
      endDate: '2024-03-16',
      currentMatchday: 22,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-05-08T14:07:30Z',
  },
  {
    id: 2022,
    area: {
      id: 2016,
      name: 'Austria',
      countryCode: 'AUT',
      ensignUrl: 'https://crests.football-data.org/816.svg',
    },
    name: 'Playoffs 1/2',
    code: 'APL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 24,
      startDate: '2018-05-31',
      endDate: '2018-06-03',
      currentMatchday: null,
      winner: {
        id: 2022,
        name: 'spusu SKN St. Pölten',
        shortName: 'St. Pölten',
        tla: 'STP',
        crestUrl: 'https://crests.football-data.org/2022.png',
      },
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-08-23T15:47:33Z',
  },
  {
    id: 2027,
    area: {
      id: 2016,
      name: 'Austria',
      countryCode: 'AUT',
      ensignUrl: 'https://crests.football-data.org/816.svg',
    },
    name: 'ÖFB Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 627,
      startDate: '2020-08-28',
      endDate: '2021-05-01',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-03-04T16:50:00Z',
  },
  {
    id: 2028,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl: 'https://crests.football-data.org/805.svg',
    },
    name: 'Coupe de Belgique',
    code: 'CB',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1638,
      startDate: '2023-09-08',
      endDate: '2024-05-09',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2023-11-15T10:48:56Z',
  },
  {
    id: 2033,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl: 'https://crests.football-data.org/805.svg',
    },
    name: 'Division 1B',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 610,
      startDate: '2020-08-21',
      endDate: '2021-05-31',
      currentMatchday: 28,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:26:53Z',
  },
  {
    id: 2009,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl: 'https://crests.football-data.org/805.svg',
    },
    name: 'Jupiler Pro League',
    code: 'BJL',
    emblemUrl: 'https://crests.football-data.org/bjl.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 2286,
      startDate: '2024-07-26',
      endDate: '2025-03-15',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2024-05-08T14:03:30Z',
  },
  {
    id: 2032,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl: 'https://crests.football-data.org/805.svg',
    },
    name: 'Playoffs',
    code: 'BJPP',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2261,
      startDate: '2024-03-29',
      endDate: '2024-05-25',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2022-05-19T20:17:51Z',
  },
  {
    id: 2010,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl: 'https://crests.football-data.org/805.svg',
    },
    name: 'Supercoupe de Belgique',
    code: 'SDB',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2305,
      startDate: '2024-07-20',
      endDate: '2024-07-20',
      currentMatchday: 0,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-06-07T11:02:11Z',
  },
  {
    id: 2034,
    area: {
      id: 2028,
      name: 'Bolivia',
      countryCode: 'BOL',
      ensignUrl: null,
    },
    name: 'LFPB',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 718,
      startDate: '2021-03-09',
      endDate: '2022-01-01',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T00:00:14Z',
  },
  {
    id: 2035,
    area: {
      id: 2030,
      name: 'Bosnia and Herzegovina',
      countryCode: 'BIH',
      ensignUrl: 'https://crests.football-data.org/bosnia.svg',
    },
    name: 'Premier Liga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 598,
      startDate: '2020-08-01',
      endDate: '2021-05-30',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T00:00:15Z',
  },
  {
    id: 2037,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: 'https://crests.football-data.org/764.svg',
    },
    name: 'Copa do Brasil',
    code: 'CDB',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1569,
      startDate: '2023-02-21',
      endDate: '2023-08-17',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2023-06-09T16:01:52Z',
  },
  {
    id: 2038,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: 'https://crests.football-data.org/764.svg',
    },
    name: 'Série D',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 595,
      startDate: '2020-05-17',
      endDate: '2020-11-22',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:26:37Z',
  },
  {
    id: 2036,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: 'https://crests.football-data.org/764.svg',
    },
    name: 'Série C',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 594,
      startDate: '2020-05-02',
      endDate: '2020-10-31',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:26:43Z',
  },
  {
    id: 2029,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: 'https://crests.football-data.org/764.svg',
    },
    name: 'Campeonato Brasileiro Série B',
    code: 'BSB',
    emblemUrl: 'https://crests.football-data.org/bsa.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 2259,
      startDate: '2024-04-19',
      endDate: '2024-11-26',
      currentMatchday: 14,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-05-08T14:08:50Z',
  },
  {
    id: 2013,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: 'https://crests.football-data.org/764.svg',
    },
    name: 'Campeonato Brasileiro Série A',
    code: 'BSA',
    emblemUrl: 'https://crests.football-data.org/bsa.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2024-05-08T14:08:14Z',
  },
  {
    id: 2039,
    area: {
      id: 2035,
      name: 'Bulgaria',
      countryCode: 'BGR',
      ensignUrl: 'https://crests.football-data.org/817.svg',
    },
    name: 'Kupa na Bulgarija',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 639,
      startDate: '2020-09-08',
      endDate: '2021-05-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:26:33Z',
  },
  {
    id: 2040,
    area: {
      id: 2035,
      name: 'Bulgaria',
      countryCode: 'BGR',
      ensignUrl: 'https://crests.football-data.org/817.svg',
    },
    name: 'A PFG',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 611,
      startDate: '2020-08-08',
      endDate: '2021-05-30',
      currentMatchday: 26,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-26T10:22:24Z',
  },
  {
    id: 2041,
    area: {
      id: 2040,
      name: 'Canada',
      countryCode: 'CAN',
      ensignUrl: null,
    },
    name: 'Canadian Championship',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 558,
      startDate: '2020-06-16',
      endDate: '2020-09-24',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:26:28Z',
  },
  {
    id: 2042,
    area: {
      id: 2045,
      name: 'Chile',
      countryCode: 'CHL',
      ensignUrl: null,
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 44,
      startDate: '2017-11-25',
      endDate: '2017-12-21',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:01:23Z',
  },
  {
    id: 2043,
    area: {
      id: 2045,
      name: 'Chile',
      countryCode: 'CHL',
      ensignUrl: null,
    },
    name: 'Supercopa de Chile',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 435,
      startDate: '2019-03-23',
      endDate: '2019-03-23',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-03-24T20:10:07Z',
  },
  {
    id: 2048,
    area: {
      id: 2045,
      name: 'Chile',
      countryCode: 'CHL',
      ensignUrl: null,
    },
    name: 'Primera División',
    code: 'CPD',
    emblemUrl: 'https://crests.football-data.org/cpd.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1652,
      startDate: '2024-02-18',
      endDate: '2024-11-10',
      currentMatchday: 16,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2024-05-08T14:09:25Z',
  },
  {
    id: 2044,
    area: {
      id: 2046,
      name: 'China PR',
      countryCode: 'CHN',
      ensignUrl: null,
    },
    name: 'Chinese Super League',
    code: 'CSL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1656,
      startDate: '2024-03-01',
      endDate: '2024-11-02',
      currentMatchday: 18,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-05-04T18:20:22Z',
  },
  {
    id: 2045,
    area: {
      id: 2049,
      name: 'Colombia',
      countryCode: 'COL',
      ensignUrl: null,
    },
    name: 'Liga Postobón',
    code: 'CLP',
    emblemUrl: 'https://crests.football-data.org/clp.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1650,
      startDate: '2024-01-19',
      endDate: '2024-04-20',
      currentMatchday: 19,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-05-08T14:09:59Z',
  },
  {
    id: 2046,
    area: {
      id: 2049,
      name: 'Colombia',
      countryCode: 'COL',
      ensignUrl: null,
    },
    name: 'Superliga de Colombia',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 438,
      startDate: '2019-01-24',
      endDate: '2019-01-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2018-06-05T00:02:32Z',
  },
  {
    id: 2047,
    area: {
      id: 2058,
      name: 'Croatia',
      countryCode: 'HRV',
      ensignUrl: 'https://crests.football-data.org/799.svg',
    },
    name: 'Prva Liga',
    code: 'PRVA',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 621,
      startDate: '2020-08-15',
      endDate: '2021-05-30',
      currentMatchday: 36,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:34:15Z',
  },
  {
    id: 2049,
    area: {
      id: 2062,
      name: 'Czech Republic',
      countryCode: 'CZE',
      ensignUrl: 'https://crests.football-data.org/798.svg',
    },
    name: 'Synot Liga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 612,
      startDate: '2020-08-22',
      endDate: '2021-05-30',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:26:23Z',
  },
  {
    id: 2051,
    area: {
      id: 2065,
      name: 'Denmark',
      countryCode: 'DNK',
      ensignUrl: 'https://crests.football-data.org/782.svg',
    },
    name: 'DBU Pokalen',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 640,
      startDate: '2020-09-01',
      endDate: '2021-05-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:26:18Z',
  },
  {
    id: 2050,
    area: {
      id: 2065,
      name: 'Denmark',
      countryCode: 'DNK',
      ensignUrl: 'https://crests.football-data.org/782.svg',
    },
    name: 'Superliga',
    code: 'DSU',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 2279,
      startDate: '2024-07-19',
      endDate: '2025-03-16',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2021-04-17T00:00:17Z',
  },
  {
    id: 2141,
    area: {
      id: 2065,
      name: 'Denmark',
      countryCode: 'DNK',
      ensignUrl: 'https://crests.football-data.org/782.svg',
    },
    name: 'Euro League - Playoff',
    code: 'DELP',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1386,
      startDate: '2020-07-11',
      endDate: '2020-07-29',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2022-04-22T10:03:12Z',
  },
  {
    id: 2052,
    area: {
      id: 2069,
      name: 'Ecuador',
      countryCode: 'ECU',
      ensignUrl: null,
    },
    name: 'Copa Pilsener Serie A',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 720,
      startDate: '2021-02-19',
      endDate: '2021-12-05',
      currentMatchday: 15,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:26:13Z',
  },
  {
    id: 2139,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'Football League Cup',
    code: 'FLC',
    emblemUrl: 'https://crests.football-data.org/FLC.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 2304,
      startDate: '2024-08-12',
      endDate: '2025-05-25',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 65,
    lastUpdated: '2022-03-20T10:14:47Z',
  },
  {
    id: 2056,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'FA Community Shield',
    code: 'COM',
    emblemUrl: 'https://crests.football-data.org/com.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2270,
      startDate: '2024-08-10',
      endDate: '2024-08-10',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 101,
    lastUpdated: '2024-05-08T14:12:07Z',
  },
  {
    id: 2055,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'FA Cup',
    code: 'FAC',
    emblemUrl: 'https://crests.football-data.org/FA_CUP.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 1574,
      startDate: '2023-11-03',
      endDate: '2024-05-25',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 143,
    lastUpdated: '2022-03-20T09:18:41Z',
  },
  {
    id: 2053,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'National League',
    code: 'ENL',
    emblemUrl: 'https://crests.football-data.org/enl.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1623,
      startDate: '2023-08-05',
      endDate: '2024-04-20',
      currentMatchday: 46,
      winner: null,
    },
    numberOfAvailableSeasons: 6,
    lastUpdated: '2024-05-08T14:11:34Z',
  },
  {
    id: 2054,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'League Two',
    code: 'EL2',
    emblemUrl: 'https://crests.football-data.org/el2.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 2303,
      startDate: '2024-08-09',
      endDate: '2025-05-03',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2024-05-08T14:11:04Z',
  },
  {
    id: 2030,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'League One',
    code: 'EL1',
    emblemUrl: 'https://crests.football-data.org/el1.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 2302,
      startDate: '2024-08-09',
      endDate: '2025-05-03',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 16,
    lastUpdated: '2024-05-08T14:10:38Z',
  },
  {
    id: 2016,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'Championship',
    code: 'ELC',
    emblemUrl: 'https://crests.football-data.org/ELC.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2301,
      startDate: '2024-08-09',
      endDate: '2025-05-03',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2022-03-20T09:31:30Z',
  },
  {
    id: 2021,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'Premier League',
    code: 'PL',
    emblemUrl: 'https://crests.football-data.org/PL.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2287,
      startDate: '2024-08-16',
      endDate: '2025-05-25',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 126,
    lastUpdated: '2022-03-20T08:58:54Z',
  },
  {
    id: 2181,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl: 'https://crests.football-data.org/770.svg',
    },
    name: 'FA Cup - Qualification',
    code: 'FACQ',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2280,
      startDate: '2022-09-02',
      endDate: '2023-03-19',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 6,
    lastUpdated: '2024-06-20T19:07:10Z',
  },
  {
    id: 2057,
    area: {
      id: 2075,
      name: 'Estonia',
      countryCode: 'EST',
      ensignUrl: 'https://crests.football-data.org/estonia.svg',
    },
    name: 'Meistriliiga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 686,
      startDate: '2021-03-05',
      endDate: '2021-11-06',
      currentMatchday: 36,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:26:10Z',
  },
  {
    id: 2146,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: 'UEFA Europa League',
    code: 'EL',
    emblemUrl: 'https://crests.football-data.org/EL.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 1627,
      startDate: '2023-08-08',
      endDate: '2024-05-22',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2022-03-20T09:23:04Z',
  },
  {
    id: 2001,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: 'UEFA Champions League',
    code: 'CL',
    emblemUrl: 'https://crests.football-data.org/CL.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 1630,
      startDate: '2023-09-19',
      endDate: '2024-06-01',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 44,
    lastUpdated: '2022-03-20T09:20:44Z',
  },
  {
    id: 2154,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: 'UEFA Conference League',
    code: 'UCL',
    emblemUrl: 'https://crests.football-data.org/UCL.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1624,
      startDate: '2023-07-12',
      endDate: '2024-05-29',
      currentMatchday: 11,
      winner: {
        id: 654,
        name: 'PAE Olympiakos SFP',
        shortName: 'Olympiakos',
        tla: 'OLY',
        crestUrl: 'https://crests.football-data.org/654.png',
      },
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2022-03-20T09:22:28Z',
  },
  {
    id: 2018,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: 'European Championship',
    code: 'EC',
    emblemUrl: 'https://crests.football-data.org/ec.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 1537,
      startDate: '2024-06-14',
      endDate: '2024-07-14',
      currentMatchday: 5,
      winner: null,
    },
    numberOfAvailableSeasons: 17,
    lastUpdated: '2024-05-08T14:14:52Z',
  },
  {
    id: 2174,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: 'Champions League Qualification',
    code: 'CLQ',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1614,
      startDate: '2023-06-27',
      endDate: '2023-08-30',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 35,
    lastUpdated: '2024-06-20T19:01:55Z',
  },
  {
    id: 2058,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: "UEFA Women's EURO",
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 62,
      startDate: '2017-07-16',
      endDate: '2017-08-06',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2020-09-07T20:55:12Z',
  },
  {
    id: 2165,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: 'European Championship Qualifiers',
    code: 'ECQ',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1538,
      startDate: '2023-03-25',
      endDate: '2023-11-19',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2022-11-08T07:42:47Z',
  },
  {
    id: 2157,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: 'UEFA Super Cup',
    code: 'ESC',
    emblemUrl: 'https://crests.football-data.org/esc.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2307,
      startDate: '2024-08-14',
      endDate: '2024-08-14',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 50,
    lastUpdated: '2024-05-08T14:13:53Z',
  },
  {
    id: 2007,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: 'https://crests.football-data.org/EUR.svg',
    },
    name: 'WC Qualification UEFA',
    code: 'QUFA',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 687,
      startDate: '2021-03-24',
      endDate: '2021-11-16',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2021-11-11T10:38:13Z',
  },
  {
    id: 2059,
    area: {
      id: 2080,
      name: 'Finland',
      countryCode: 'FIN',
      ensignUrl: 'https://crests.football-data.org/1976.svg',
    },
    name: 'Suomen Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 689,
      startDate: '2021-01-24',
      endDate: '2021-10-31',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:26:05Z',
  },
  {
    id: 2031,
    area: {
      id: 2080,
      name: 'Finland',
      countryCode: 'FIN',
      ensignUrl: 'https://crests.football-data.org/1976.svg',
    },
    name: 'Veikkausliiga',
    code: 'VEI',
    emblemUrl: 'https://crests.football-data.org/vei.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1653,
      startDate: '2024-04-06',
      endDate: '2024-09-01',
      currentMatchday: 17,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-05-08T14:16:37Z',
  },
  {
    id: 2135,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl: 'https://crests.football-data.org/773.svg',
    },
    name: 'Coupe de la Ligue',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 522,
      startDate: '2019-08-13',
      endDate: '2020-04-04',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:26:01Z',
  },
  {
    id: 2142,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl: 'https://crests.football-data.org/773.svg',
    },
    name: 'Ligue 2',
    code: 'FL2',
    emblemUrl: 'https://crests.football-data.org/FL2.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 2291,
      startDate: '2024-08-17',
      endDate: '2025-05-10',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 27,
    lastUpdated: '2022-03-20T09:34:19Z',
  },
  {
    id: 2015,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl: 'https://crests.football-data.org/773.svg',
    },
    name: 'Ligue 1',
    code: 'FL1',
    emblemUrl: 'https://crests.football-data.org/FL1.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2290,
      startDate: '2024-08-18',
      endDate: '2025-05-18',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 81,
    lastUpdated: '2022-03-20T09:30:02Z',
  },
  {
    id: 2138,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl: 'https://crests.football-data.org/773.svg',
    },
    name: 'Coupe de France',
    code: 'CDF',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2268,
      startDate: '2023-11-17',
      endDate: '2024-05-25',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2024-05-25T18:23:46Z',
  },
  {
    id: 2143,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl: 'https://crests.football-data.org/773.svg',
    },
    name: 'Playoffs 1/2',
    code: 'FPL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1483,
      startDate: '2022-05-17',
      endDate: '2022-05-20',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2022-05-19T19:56:53Z',
  },
  {
    id: 2136,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl: 'https://crests.football-data.org/773.svg',
    },
    name: 'Trophée des Champions',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 655,
      startDate: '2021-01-01',
      endDate: '2021-01-31',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-01-14T17:55:00Z',
  },
  {
    id: 2144,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl: 'https://crests.football-data.org/773.svg',
    },
    name: 'Playoffs 2/3',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 212,
      startDate: '2018-05-22',
      endDate: '2018-05-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-09-25T15:07:37Z',
  },
  {
    id: 2011,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'DFB-Pokal',
    code: 'DFB',
    emblemUrl: 'https://crests.football-data.org/DFB_CUP.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 2271,
      startDate: '2024-08-16',
      endDate: '2025-05-24',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 69,
    lastUpdated: '2022-03-20T09:21:19Z',
  },
  {
    id: 2129,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Regionalliga',
    code: 'REG',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 760,
      startDate: '2021-07-15',
      endDate: '2022-05-21',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2023-05-01T08:21:04Z',
  },
  {
    id: 2140,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: '3. Bundesliga',
    code: 'BL3',
    emblemUrl: 'https://crests.football-data.org/BL3.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1607,
      startDate: '2023-08-05',
      endDate: '2024-05-18',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 12,
    lastUpdated: '2022-03-20T10:38:24Z',
  },
  {
    id: 2004,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: '2. Bundesliga',
    code: 'BL2',
    emblemUrl: 'https://crests.football-data.org/BL2.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 2309,
      startDate: '2024-08-02',
      endDate: '2025-05-18',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 29,
    lastUpdated: '2022-03-20T08:57:46Z',
  },
  {
    id: 2002,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Bundesliga',
    code: 'BL1',
    emblemUrl: 'https://crests.football-data.org/BL1.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2308,
      startDate: '2024-08-23',
      endDate: '2025-05-17',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 62,
    lastUpdated: '2022-03-20T08:52:53Z',
  },
  {
    id: 2172,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Regionalliga Nord',
    code: 'RLN',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1611,
      startDate: '2023-07-28',
      endDate: '2024-05-18',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2024-06-20T19:01:36Z',
  },
  {
    id: 2133,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Frauen Bundesliga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 142,
      startDate: '2017-09-02',
      endDate: '2018-06-03',
      currentMatchday: 22,
      winner: {
        id: 7522,
        name: 'VfL Wolfsburg',
        shortName: null,
        tla: null,
        crestUrl: null,
      },
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:09:39Z',
  },
  {
    id: 2159,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Regionalliga Bayern',
    code: 'RBY',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2300,
      startDate: '2024-07-18',
      endDate: '2025-05-17',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2022-07-20T10:36:06Z',
  },
  {
    id: 2134,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'DFL Super Cup',
    code: 'GSC',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2269,
      startDate: '2024-08-17',
      endDate: '2024-08-17',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 25,
    lastUpdated: '2023-02-27T19:12:59Z',
  },
  {
    id: 2168,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Regionalliga West',
    code: 'RLW',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1610,
      startDate: '2023-07-28',
      endDate: '2024-05-18',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2024-06-20T19:00:50Z',
  },
  {
    id: 2160,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Regionalliga Südwest',
    code: 'RSW',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1606,
      startDate: '2023-08-05',
      endDate: '2024-05-18',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2023-07-17T12:44:01Z',
  },
  {
    id: 2156,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Relegation',
    code: 'BLREL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2260,
      startDate: '2024-05-23',
      endDate: '2024-05-28',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2022-05-19T20:17:34Z',
  },
  {
    id: 2169,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl: 'https://crests.football-data.org/759.svg',
    },
    name: 'Regionalliga Nordost',
    code: 'RNO',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1601,
      startDate: '2023-07-30',
      endDate: '2024-05-19',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2024-06-20T19:01:00Z',
  },
  {
    id: 2131,
    area: {
      id: 2093,
      name: 'Greece',
      countryCode: 'GRC',
      ensignUrl: 'https://crests.football-data.org/775.svg',
    },
    name: 'Greek Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 656,
      startDate: '2020-11-01',
      endDate: '2021-05-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:25:53Z',
  },
  {
    id: 2132,
    area: {
      id: 2093,
      name: 'Greece',
      countryCode: 'GRC',
      ensignUrl: 'https://crests.football-data.org/775.svg',
    },
    name: 'Super League',
    code: 'GSL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1613,
      startDate: '2023-08-18',
      endDate: '2024-05-19',
      currentMatchday: 26,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-05-05T09:12:51Z',
  },
  {
    id: 2150,
    area: {
      id: 2093,
      name: 'Greece',
      countryCode: 'GRC',
      ensignUrl: 'https://crests.football-data.org/775.svg',
    },
    name: 'Souper Kap Ellados',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 684,
      startDate: '2007-10-31',
      endDate: '2007-10-31',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-06-20T18:59:02Z',
  },
  {
    id: 2130,
    area: {
      id: 2106,
      name: 'Hungary',
      countryCode: 'HUN',
      ensignUrl: 'https://crests.football-data.org/827.svg',
    },
    name: 'Magyar Kupa',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 696,
      startDate: '2020-09-16',
      endDate: '2021-05-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:25:47Z',
  },
  {
    id: 2128,
    area: {
      id: 2106,
      name: 'Hungary',
      countryCode: 'HUN',
      ensignUrl: 'https://crests.football-data.org/827.svg',
    },
    name: 'NB I',
    code: 'HNB',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1587,
      startDate: '2023-07-29',
      endDate: '2024-05-25',
      currentMatchday: 33,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-04-17T00:00:21Z',
  },
  {
    id: 2127,
    area: {
      id: 2107,
      name: 'Iceland',
      countryCode: 'ISL',
      ensignUrl: 'https://crests.football-data.org/iceland.svg',
    },
    name: 'Úrvalsdeild',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 585,
      startDate: '2020-04-22',
      endDate: '2020-09-26',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:25:42Z',
  },
  {
    id: 2126,
    area: {
      id: 2108,
      name: 'India',
      countryCode: 'IND',
      ensignUrl: null,
    },
    name: 'I-League',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 676,
      startDate: '2021-01-09',
      endDate: '2021-05-30',
      currentMatchday: 11,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:33:44Z',
  },
  {
    id: 2161,
    area: {
      id: 2108,
      name: 'India',
      countryCode: 'IND',
      ensignUrl: null,
    },
    name: 'Indian Super League',
    code: 'ISL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: null,
    numberOfAvailableSeasons: 0,
    lastUpdated: '2022-07-26T11:21:45Z',
  },
  {
    id: 2125,
    area: {
      id: 2113,
      name: 'Israel',
      countryCode: 'ISR',
      ensignUrl: 'https://crests.football-data.org/israel.svg',
    },
    name: "Ligat ha'Al",
    code: 'ILH',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1633,
      startDate: '2023-08-26',
      endDate: '2024-03-17',
      currentMatchday: 26,
      winner: {
        id: 5929,
        name: 'Maccabi Tel Aviv FC',
        shortName: 'Maccabi TA',
        tla: 'MTA',
        crestUrl: 'https://crests.football-data.org/5929.png',
      },
    },
    numberOfAvailableSeasons: 6,
    lastUpdated: '2022-12-28T09:29:37Z',
  },
  {
    id: 2124,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Supercoppa',
    code: 'ISC',
    emblemUrl: 'https://crests.football-data.org/isc.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1648,
      startDate: '2024-01-18',
      endDate: '2024-01-22',
      currentMatchday: 0,
      winner: null,
    },
    numberOfAvailableSeasons: 34,
    lastUpdated: '2024-01-13T10:55:20Z',
  },
  {
    id: 2122,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Coppa Italia',
    code: 'CIT',
    emblemUrl: 'https://crests.football-data.org/CIT.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1615,
      startDate: '2023-08-05',
      endDate: '2024-01-11',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2022-03-20T09:33:08Z',
  },
  {
    id: 2123,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Serie C',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 767,
      startDate: '2021-07-23',
      endDate: '2022-05-12',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2024-01-11T08:29:19Z',
  },
  {
    id: 2121,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Serie B',
    code: 'SB',
    emblemUrl: 'https://crests.football-data.org/SB.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 1608,
      startDate: '2023-08-19',
      endDate: '2024-05-10',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 19,
    lastUpdated: '2022-03-20T09:38:51Z',
  },
  {
    id: 2019,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Serie A',
    code: 'SA',
    emblemUrl: 'https://crests.football-data.org/SA.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2310,
      startDate: '2024-08-18',
      endDate: '2025-05-25',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 93,
    lastUpdated: '2022-03-20T09:16:43Z',
  },
  {
    id: 2158,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Playoffs 1/2',
    code: 'IPL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1487,
      startDate: '2022-11-21',
      endDate: '2023-06-01',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-06-20T19:05:01Z',
  },
  {
    id: 2163,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Serie C - Girone B',
    code: 'ISCB',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1620,
      startDate: '2023-09-03',
      endDate: '2024-04-28',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2022-09-02T09:20:36Z',
  },
  {
    id: 2164,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Serie C - Girone C',
    code: 'ISCC',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1629,
      startDate: '2023-09-01',
      endDate: '2024-04-28',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2022-09-02T09:20:42Z',
  },
  {
    id: 2162,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl: 'https://crests.football-data.org/784.svg',
    },
    name: 'Serie C - Girone A',
    code: 'ISCA',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1619,
      startDate: '2023-09-03',
      endDate: '2024-04-28',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2022-08-13T13:08:43Z',
  },
  {
    id: 2118,
    area: {
      id: 2116,
      name: 'Japan',
      countryCode: 'JPN',
      ensignUrl: 'https://crests.football-data.org/JAP.svg',
    },
    name: 'J.League Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 581,
      startDate: '2020-02-16',
      endDate: '2020-10-31',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:29:34Z',
  },
  {
    id: 2117,
    area: {
      id: 2116,
      name: 'Japan',
      countryCode: 'JPN',
      ensignUrl: 'https://crests.football-data.org/JAP.svg',
    },
    name: 'J. League Division 2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 694,
      startDate: '2021-02-27',
      endDate: '2021-12-05',
      currentMatchday: 42,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:29:38Z',
  },
  {
    id: 2119,
    area: {
      id: 2116,
      name: 'Japan',
      countryCode: 'JPN',
      ensignUrl: 'https://crests.football-data.org/JAP.svg',
    },
    name: 'J. League',
    code: 'JJL',
    emblemUrl: 'https://crests.football-data.org/jjl.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 1654,
      startDate: '2024-02-23',
      endDate: '2024-12-08',
      currentMatchday: 22,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-05-08T14:17:32Z',
  },
  {
    id: 2120,
    area: {
      id: 2116,
      name: 'Japan',
      countryCode: 'JPN',
      ensignUrl: 'https://crests.football-data.org/JAP.svg',
    },
    name: 'Super Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 695,
      startDate: '2021-02-20',
      endDate: '2021-02-23',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-02-20T08:30:26Z',
  },
  {
    id: 2116,
    area: {
      id: 2129,
      name: 'Latvia',
      countryCode: 'LVA',
      ensignUrl: 'https://crests.football-data.org/latvia.svg',
    },
    name: 'Virslīga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 579,
      startDate: '2020-03-13',
      endDate: '2020-11-14',
      currentMatchday: 36,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:29:30Z',
  },
  {
    id: 2115,
    area: {
      id: 2135,
      name: 'Lithuania',
      countryCode: 'LTU',
      ensignUrl: 'https://crests.football-data.org/1983.svg',
    },
    name: 'A Lyga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 590,
      startDate: '2020-03-06',
      endDate: '2020-11-07',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:29:27Z',
  },
  {
    id: 2114,
    area: {
      id: 2143,
      name: 'Malta',
      countryCode: 'MLT',
      ensignUrl: 'https://crests.football-data.org/malta.svg',
    },
    name: 'Premier League',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 633,
      startDate: '2020-09-11',
      endDate: '2021-05-30',
      currentMatchday: 28,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:29:24Z',
  },
  {
    id: 2112,
    area: {
      id: 2149,
      name: 'Mexico',
      countryCode: 'MEX',
      ensignUrl: 'https://crests.football-data.org/mexico.svg',
    },
    name: 'SuperCopa MX',
    code: 'SCMX',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1535,
      startDate: '2022-06-27',
      endDate: '2022-06-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2022-11-08T07:21:43Z',
  },
  {
    id: 2111,
    area: {
      id: 2149,
      name: 'Mexico',
      countryCode: 'MEX',
      ensignUrl: 'https://crests.football-data.org/mexico.svg',
    },
    name: 'Copa MX',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 479,
      startDate: '2019-07-30',
      endDate: '2020-04-15',
      currentMatchday: 7,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:29:21Z',
  },
  {
    id: 2113,
    area: {
      id: 2149,
      name: 'Mexico',
      countryCode: 'MEX',
      ensignUrl: 'https://crests.football-data.org/mexico.svg',
    },
    name: 'Liga MX',
    code: 'LMX',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1570,
      startDate: '2023-07-01',
      endDate: '2024-04-29',
      currentMatchday: 17,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-04-17T07:19:46Z',
  },
  {
    id: 2109,
    area: {
      id: 2163,
      name: 'Netherlands',
      countryCode: 'NLD',
      ensignUrl: 'https://crests.football-data.org/8601.svg',
    },
    name: 'KNVB Beker',
    code: 'KNV',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1605,
      startDate: '2023-08-12',
      endDate: '2024-05-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-04-17T00:00:25Z',
  },
  {
    id: 2005,
    area: {
      id: 2163,
      name: 'Netherlands',
      countryCode: 'NLD',
      ensignUrl: 'https://crests.football-data.org/8601.svg',
    },
    name: 'Eerste Divisie',
    code: 'DJL',
    emblemUrl: 'https://crests.football-data.org/djl.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1589,
      startDate: '2023-08-11',
      endDate: '2024-05-10',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-05-08T14:18:02Z',
  },
  {
    id: 2003,
    area: {
      id: 2163,
      name: 'Netherlands',
      countryCode: 'NLD',
      ensignUrl: 'https://crests.football-data.org/8601.svg',
    },
    name: 'Eredivisie',
    code: 'DED',
    emblemUrl: 'https://crests.football-data.org/ED.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2293,
      startDate: '2024-08-09',
      endDate: '2025-05-18',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 69,
    lastUpdated: '2022-03-20T09:19:27Z',
  },
  {
    id: 2110,
    area: {
      id: 2163,
      name: 'Netherlands',
      countryCode: 'NLD',
      ensignUrl: 'https://crests.football-data.org/8601.svg',
    },
    name: 'Johan Cruijff Schaal',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 483,
      startDate: '2019-07-27',
      endDate: '2019-07-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-07-28T00:20:08Z',
  },
  {
    id: 2108,
    area: {
      id: 2171,
      name: 'Northern Ireland',
      countryCode: 'NIR',
      ensignUrl: 'https://crests.football-data.org/829.svg',
    },
    name: 'League Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 528,
      startDate: '2019-08-10',
      endDate: '2020-02-15',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:29:13Z',
  },
  {
    id: 2107,
    area: {
      id: 2171,
      name: 'Northern Ireland',
      countryCode: 'NIR',
      ensignUrl: 'https://crests.football-data.org/829.svg',
    },
    name: 'Premiership',
    code: 'NIP',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1622,
      startDate: '2023-08-04',
      endDate: '2024-03-23',
      currentMatchday: 33,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2022-11-16T12:41:43Z',
  },
  {
    id: 2106,
    area: {
      id: 2173,
      name: 'Norway',
      countryCode: 'NOR',
      ensignUrl: 'https://crests.football-data.org/813.svg',
    },
    name: 'Tippeligaen',
    code: 'TIP',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1646,
      startDate: '2024-03-31',
      endDate: '2024-12-01',
      currentMatchday: 18,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-04-17T00:00:26Z',
  },
  {
    id: 2105,
    area: {
      id: 2173,
      name: 'Norway',
      countryCode: 'NOR',
      ensignUrl: 'https://crests.football-data.org/813.svg',
    },
    name: '1. divisjon',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 699,
      startDate: '2021-04-06',
      endDate: '2021-11-06',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:29:10Z',
  },
  {
    id: 2104,
    area: {
      id: 2173,
      name: 'Norway',
      countryCode: 'NOR',
      ensignUrl: 'https://crests.football-data.org/813.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 112,
      startDate: '2017-11-29',
      endDate: '2017-12-02',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:20:23Z',
  },
  {
    id: 2103,
    area: {
      id: 2175,
      name: 'Oceania',
      countryCode: 'OCE',
      ensignUrl: null,
    },
    name: 'WC Qualification OFC',
    code: 'QOFC',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 111,
      startDate: '2015-08-31',
      endDate: '2017-09-05',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2021-11-09T14:49:43Z',
  },
  {
    id: 2102,
    area: {
      id: 2181,
      name: 'Panama',
      countryCode: 'PAN',
      ensignUrl: null,
    },
    name: 'Liga Panameña de Fútbol',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 701,
      startDate: '2021-02-19',
      endDate: '2021-11-28',
      currentMatchday: 16,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2021-04-17T11:29:07Z',
  },
  {
    id: 2101,
    area: {
      id: 2184,
      name: 'Peru',
      countryCode: 'PER',
      ensignUrl: null,
    },
    name: 'Primera División',
    code: 'PPD',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1649,
      startDate: '2024-01-26',
      endDate: '2024-05-17',
      currentMatchday: 16,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-04-16T05:06:37Z',
  },
  {
    id: 2099,
    area: {
      id: 2186,
      name: 'Poland',
      countryCode: 'POL',
      ensignUrl: 'https://crests.football-data.org/794.svg',
    },
    name: 'Superpuchar Polski',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 607,
      startDate: '2020-08-09',
      endDate: '2020-08-09',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-10T14:30:08Z',
  },
  {
    id: 2100,
    area: {
      id: 2186,
      name: 'Poland',
      countryCode: 'POL',
      ensignUrl: 'https://crests.football-data.org/794.svg',
    },
    name: 'Puchar Polski',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 643,
      startDate: '2020-08-08',
      endDate: '2021-05-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-15T14:10:05Z',
  },
  {
    id: 2098,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'POR',
      ensignUrl: 'https://crests.football-data.org/765.svg',
    },
    name: 'Taça de Portugal',
    code: 'TDP',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1641,
      startDate: '2023-09-23',
      endDate: '2023-11-26',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 6,
    lastUpdated: '2023-11-21T15:45:39Z',
  },
  {
    id: 2096,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'POR',
      ensignUrl: 'https://crests.football-data.org/765.svg',
    },
    name: 'Liga2 Cabovisão',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 645,
      startDate: '2020-09-13',
      endDate: '2021-05-19',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:29:03Z',
  },
  {
    id: 2017,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'POR',
      ensignUrl: 'https://crests.football-data.org/765.svg',
    },
    name: 'Primeira Liga',
    code: 'PPL',
    emblemUrl: 'https://crests.football-data.org/PPL.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 1603,
      startDate: '2023-08-13',
      endDate: '2024-05-19',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 75,
    lastUpdated: '2022-03-20T09:34:09Z',
  },
  {
    id: 2097,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'POR',
      ensignUrl: 'https://crests.football-data.org/765.svg',
    },
    name: 'Supertaça Cândido de Oliveira',
    code: 'SCO',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2276,
      startDate: '2024-08-03',
      endDate: '2024-08-03',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 6,
    lastUpdated: '2023-08-04T15:20:51Z',
  },
  {
    id: 2177,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'POR',
      ensignUrl: 'https://crests.football-data.org/765.svg',
    },
    name: 'Taça da Liga',
    code: 'TDL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1640,
      startDate: '2023-07-21',
      endDate: '2024-01-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2023-11-23T12:03:32Z',
  },
  {
    id: 2095,
    area: {
      id: 2192,
      name: 'Republic of Ireland',
      countryCode: 'IRL',
      ensignUrl: 'https://crests.football-data.org/806.svg',
    },
    name: 'Premier Division',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 574,
      startDate: '2020-02-14',
      endDate: '2020-10-23',
      currentMatchday: 35,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-17T11:28:53Z',
  },
  {
    id: 2092,
    area: {
      id: 2194,
      name: 'Romania',
      countryCode: 'ROU',
      ensignUrl: 'https://crests.football-data.org/811.svg',
    },
    name: 'Liga II',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 713,
      startDate: '2020-08-29',
      endDate: '2021-05-30',
      currentMatchday: 21,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:28:49Z',
  },
  {
    id: 2094,
    area: {
      id: 2194,
      name: 'Romania',
      countryCode: 'ROU',
      ensignUrl: 'https://crests.football-data.org/811.svg',
    },
    name: 'Liga I',
    code: 'RL1',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1583,
      startDate: '2023-07-14',
      endDate: '2024-03-09',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-04-17T00:00:27Z',
  },
  {
    id: 2093,
    area: {
      id: 2194,
      name: 'Romania',
      countryCode: 'ROU',
      ensignUrl: 'https://crests.football-data.org/811.svg',
    },
    name: 'Supercupa României',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 515,
      startDate: '2019-07-13',
      endDate: '2019-07-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-07-07T00:20:01Z',
  },
  {
    id: 2089,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl: 'https://crests.football-data.org/808.svg',
    },
    name: 'Russian Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 646,
      startDate: '2020-08-05',
      endDate: '2021-05-12',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:28:45Z',
  },
  {
    id: 2088,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl: 'https://crests.football-data.org/808.svg',
    },
    name: 'FNL',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 634,
      startDate: '2020-08-01',
      endDate: '2021-10-03',
      currentMatchday: 42,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:32:31Z',
  },
  {
    id: 2137,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl: 'https://crests.football-data.org/808.svg',
    },
    name: 'RFPL',
    code: 'RFPL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 1582,
      startDate: '2023-07-22',
      endDate: '2024-05-25',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-04-17T00:00:27Z',
  },
  {
    id: 2090,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl: 'https://crests.football-data.org/808.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 96,
      startDate: '2018-05-17',
      endDate: '2018-05-20',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:24:32Z',
  },
  {
    id: 2091,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl: 'https://crests.football-data.org/808.svg',
    },
    name: 'Russian Super Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 647,
      startDate: '2020-08-07',
      endDate: '2020-08-07',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2019-07-07T00:25:01Z',
  },
  {
    id: 2087,
    area: {
      id: 2204,
      name: 'Scotland',
      countryCode: 'SCO',
      ensignUrl: 'https://crests.football-data.org/814.svg',
    },
    name: 'Scottish Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 703,
      startDate: '2020-11-28',
      endDate: '2021-05-08',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:28:39Z',
  },
  {
    id: 2085,
    area: {
      id: 2204,
      name: 'Scotland',
      countryCode: 'SCO',
      ensignUrl: 'https://crests.football-data.org/814.svg',
    },
    name: 'Championship',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 608,
      startDate: '2020-10-17',
      endDate: '2021-05-30',
      currentMatchday: 27,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:28:42Z',
  },
  {
    id: 2084,
    area: {
      id: 2204,
      name: 'Scotland',
      countryCode: 'SCO',
      ensignUrl: 'https://crests.football-data.org/814.svg',
    },
    name: 'Premier League',
    code: 'SPL',
    emblemUrl: 'https://crests.football-data.org/SPL.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 2306,
      startDate: '2024-08-03',
      endDate: '2025-04-12',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 128,
    lastUpdated: '2022-03-20T09:35:15Z',
  },
  {
    id: 2086,
    area: {
      id: 2204,
      name: 'Scotland',
      countryCode: 'SCO',
      ensignUrl: 'https://crests.football-data.org/814.svg',
    },
    name: 'Playoffs 2/3',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 92,
      startDate: '2018-05-02',
      endDate: '2018-05-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:25:54Z',
  },
  {
    id: 2173,
    area: {
      id: 2215,
      name: 'Slovenia',
      countryCode: 'SVN',
      ensignUrl: null,
    },
    name: 'PrvaLiga',
    code: 'SPRV',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1585,
      startDate: '2023-07-22',
      endDate: '2024-05-18',
      currentMatchday: 36,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-06-20T19:01:44Z',
  },
  {
    id: 2083,
    area: {
      id: 2219,
      name: 'South Africa',
      countryCode: 'RSA',
      ensignUrl: null,
    },
    name: 'ABSA Premiership',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 704,
      startDate: '2020-10-24',
      endDate: '2021-05-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:28:35Z',
  },
  {
    id: 2152,
    area: {
      id: 2220,
      name: 'South America',
      countryCode: 'SAM',
      ensignUrl: 'https://crests.football-data.org/CLI.svg',
    },
    name: 'Copa Libertadores',
    code: 'CLI',
    emblemUrl: 'https://crests.football-data.org/CLI.svg',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 1644,
      startDate: '2024-02-07',
      endDate: '2024-05-31',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2024-06-20T18:59:19Z',
  },
  {
    id: 2080,
    area: {
      id: 2220,
      name: 'South America',
      countryCode: 'SAM',
      ensignUrl: 'https://crests.football-data.org/CLI.svg',
    },
    name: 'Copa America',
    code: 'CA',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1642,
      startDate: '2024-06-20',
      endDate: '2024-07-14',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-05-25T10:09:19Z',
  },
  {
    id: 2081,
    area: {
      id: 2220,
      name: 'South America',
      countryCode: 'SAM',
      ensignUrl: 'https://crests.football-data.org/CLI.svg',
    },
    name: 'Copa Sudamericana',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 723,
      startDate: '2021-03-16',
      endDate: '2021-11-06',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:28:31Z',
  },
  {
    id: 2082,
    area: {
      id: 2220,
      name: 'South America',
      countryCode: 'SAM',
      ensignUrl: 'https://crests.football-data.org/CLI.svg',
    },
    name: 'WC Qualification CONMEBOL',
    code: 'QCBL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1599,
      startDate: '2023-09-06',
      endDate: '2025-09-06',
      currentMatchday: 7,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-11-11T10:35:28Z',
  },
  {
    id: 2079,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl: 'https://crests.football-data.org/760.svg',
    },
    name: 'Copa del Rey',
    code: 'CDR',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1635,
      startDate: '2023-10-11',
      endDate: '2024-04-27',
      currentMatchday: 2,
      winner: {
        id: 77,
        name: 'Athletic Club',
        shortName: 'Athletic',
        tla: 'ATH',
        crestUrl: 'https://crests.football-data.org/77.png',
      },
    },
    numberOfAvailableSeasons: 118,
    lastUpdated: '2021-04-16T00:00:33Z',
  },
  {
    id: 2077,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl: 'https://crests.football-data.org/760.svg',
    },
    name: 'Segunda División',
    code: 'SD',
    emblemUrl: 'https://crests.football-data.org/SD.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 1602,
      startDate: '2023-08-13',
      endDate: '2024-06-02',
      currentMatchday: 42,
      winner: null,
    },
    numberOfAvailableSeasons: 12,
    lastUpdated: '2022-03-20T09:35:51Z',
  },
  {
    id: 2014,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl: 'https://crests.football-data.org/760.svg',
    },
    name: 'Primera Division',
    code: 'PD',
    emblemUrl: 'https://crests.football-data.org/PD.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2292,
      startDate: '2024-08-18',
      endDate: '2025-05-25',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 94,
    lastUpdated: '2022-03-20T09:20:08Z',
  },
  {
    id: 2179,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl: 'https://crests.football-data.org/760.svg',
    },
    name: 'La Liga Play-Offs',
    code: 'LLP',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2272,
      startDate: '2024-06-08',
      endDate: '2024-06-23',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-06-20T19:06:37Z',
  },
  {
    id: 2078,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl: 'https://crests.football-data.org/760.svg',
    },
    name: 'Supercopa de España',
    code: 'SDE',
    emblemUrl: 'https://crests.football-data.org/sde.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1647,
      startDate: '2024-01-10',
      endDate: '2024-01-14',
      currentMatchday: 0,
      winner: null,
    },
    numberOfAvailableSeasons: 44,
    lastUpdated: '2024-01-13T10:54:15Z',
  },
  {
    id: 2074,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl: 'https://crests.football-data.org/792.svg',
    },
    name: 'Superettan',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 710,
      startDate: '2021-04-10',
      endDate: '2021-11-27',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:28:27Z',
  },
  {
    id: 2073,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl: 'https://crests.football-data.org/792.svg',
    },
    name: 'Allsvenskan',
    code: 'ALL',
    emblemUrl: 'https://crests.football-data.org/all.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1645,
      startDate: '2024-03-30',
      endDate: '2024-11-10',
      currentMatchday: 17,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-05-08T14:19:10Z',
  },
  {
    id: 2151,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl: 'https://crests.football-data.org/792.svg',
    },
    name: 'Svenska Supercupen',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 711,
      startDate: '2015-11-08',
      endDate: '2015-11-08',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-06-20T18:59:10Z',
  },
  {
    id: 2075,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl: 'https://crests.football-data.org/792.svg',
    },
    name: 'Playoffs 2/3',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 79,
      startDate: '2017-11-08',
      endDate: '2017-11-11',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:28:43Z',
  },
  {
    id: 2076,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl: 'https://crests.football-data.org/792.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 80,
      startDate: '2017-11-15',
      endDate: '2017-11-19',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:28:54Z',
  },
  {
    id: 2071,
    area: {
      id: 2234,
      name: 'Switzerland',
      countryCode: 'CHE',
      ensignUrl: 'https://crests.football-data.org/788.svg',
    },
    name: 'Schweizer Pokal',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 660,
      startDate: '2020-08-28',
      endDate: '2021-05-24',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T10:02:19Z',
  },
  {
    id: 2072,
    area: {
      id: 2234,
      name: 'Switzerland',
      countryCode: 'CHE',
      ensignUrl: 'https://crests.football-data.org/788.svg',
    },
    name: 'Super League',
    code: 'SSL',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 2294,
      startDate: '2024-07-20',
      endDate: '2025-02-04',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2021-04-17T00:00:29Z',
  },
  {
    id: 2068,
    area: {
      id: 2247,
      name: 'Turkey',
      countryCode: 'TUR',
      ensignUrl: 'https://crests.football-data.org/803.svg',
    },
    name: '1. Lig',
    code: 'T1L',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1621,
      startDate: '2023-08-11',
      endDate: '2024-05-12',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 6,
    lastUpdated: '2022-07-26T09:36:02Z',
  },
  {
    id: 2070,
    area: {
      id: 2247,
      name: 'Turkey',
      countryCode: 'TUR',
      ensignUrl: 'https://crests.football-data.org/803.svg',
    },
    name: 'Süper Lig',
    code: 'TSL',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1612,
      startDate: '2023-08-13',
      endDate: '2024-07-19',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2021-04-17T00:00:29Z',
  },
  {
    id: 2069,
    area: {
      id: 2247,
      name: 'Turkey',
      countryCode: 'TUR',
      ensignUrl: 'https://crests.football-data.org/803.svg',
    },
    name: 'TFF Süper Kupa',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 708,
      startDate: '2021-01-27',
      endDate: '2021-01-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2019-08-07T21:11:21Z',
  },
  {
    id: 2065,
    area: {
      id: 2253,
      name: 'Ukraine',
      countryCode: 'UKR',
      ensignUrl: 'https://crests.football-data.org/790.svg',
    },
    name: 'Kubok Ukrainy',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 551,
      startDate: '2019-08-07',
      endDate: '2020-07-08',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2021-04-06T14:22:39Z',
  },
  {
    id: 2064,
    area: {
      id: 2253,
      name: 'Ukraine',
      countryCode: 'UKR',
      ensignUrl: 'https://crests.football-data.org/790.svg',
    },
    name: 'Premier Liha',
    code: 'UPL',
    emblemUrl: 'https://crests.football-data.org/upl.png',
    plan: 'TIER_THREE',
    currentSeason: {
      id: 1604,
      startDate: '2023-07-29',
      endDate: '2024-05-25',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 7,
    lastUpdated: '2024-01-13T11:45:52Z',
  },
  {
    id: 2067,
    area: {
      id: 2253,
      name: 'Ukraine',
      countryCode: 'UKR',
      ensignUrl: 'https://crests.football-data.org/790.svg',
    },
    name: 'Superkubok Ukrainy',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 648,
      startDate: '2020-08-25',
      endDate: '2020-08-25',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2019-07-28T23:59:39Z',
  },
  {
    id: 2066,
    area: {
      id: 2253,
      name: 'Ukraine',
      countryCode: 'UKR',
      ensignUrl: 'https://crests.football-data.org/790.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 70,
      startDate: '2018-05-23',
      endDate: '2018-05-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-02T14:03:07Z',
  },
  {
    id: 2145,
    area: {
      id: 2256,
      name: 'United States',
      countryCode: 'USA',
      ensignUrl: 'https://crests.football-data.org/usa.svg',
    },
    name: 'MLS',
    code: 'MLS',
    emblemUrl: 'https://crests.football-data.org/MLS.png',
    plan: 'TIER_TWO',
    currentSeason: {
      id: 1643,
      startDate: '2024-02-22',
      endDate: '2024-10-20',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 5,
    lastUpdated: '2022-03-20T09:23:49Z',
  },
  {
    id: 2175,
    area: {
      id: 2256,
      name: 'United States',
      countryCode: 'USA',
      ensignUrl: 'https://crests.football-data.org/usa.svg',
    },
    name: 'MLS - Playoffs',
    code: 'MLSP',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1636,
      startDate: '2023-10-25',
      endDate: '2023-12-09',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-06-20T19:06:23Z',
  },
  {
    id: 2063,
    area: {
      id: 2257,
      name: 'Uruguay',
      countryCode: 'URY',
      ensignUrl: null,
    },
    name: 'Primera División',
    code: 'UPD',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2289,
      startDate: '2024-06-08',
      endDate: '2024-07-20',
      currentMatchday: 5,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2024-06-22T09:43:03Z',
  },
  {
    id: 2148,
    area: {
      id: 2257,
      name: 'Uruguay',
      countryCode: 'URY',
      ensignUrl: null,
    },
    name: 'Supercopa Uruguay',
    code: 'SUCU',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 569,
      startDate: '2020-02-01',
      endDate: '2020-02-01',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-06-20T18:58:20Z',
  },
  {
    id: 2062,
    area: {
      id: 2262,
      name: 'Venezuela',
      countryCode: 'VEN',
      ensignUrl: null,
    },
    name: 'Primera División',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 722,
      startDate: '2021-04-04',
      endDate: '2021-11-28',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T11:28:17Z',
  },
  {
    id: 2061,
    area: {
      id: 2263,
      name: 'Vietnam',
      countryCode: 'VIE',
      ensignUrl: null,
    },
    name: 'V-League',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 705,
      startDate: '2021-01-24',
      endDate: '2021-10-31',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2021-04-17T00:00:31Z',
  },
  {
    id: 2060,
    area: {
      id: 2264,
      name: 'Wales',
      countryCode: 'WAL',
      ensignUrl: 'https://crests.football-data.org/833.svg',
    },
    name: 'Welsh Premier League',
    code: 'WPL',
    emblemUrl: 'https://crests.football-data.org/welsh.png',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2299,
      startDate: '2024-08-09',
      endDate: '2025-01-11',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2024-06-27T11:52:33Z',
  },
  {
    id: 2178,
    area: {
      id: 2267,
      name: 'World',
      countryCode: 'INT',
      ensignUrl: null,
    },
    name: 'FIFA Club World Cup',
    code: 'FCWC',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1871,
      startDate: '2024-12-12',
      endDate: '2024-12-22',
      currentMatchday: 0,
      winner: null,
    },
    numberOfAvailableSeasons: 20,
    lastUpdated: '2024-02-26T08:25:43Z',
  },
  {
    id: 2180,
    area: {
      id: 2267,
      name: 'World',
      countryCode: 'INT',
      ensignUrl: null,
    },
    name: 'Club Friendlies',
    code: 'CLF',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 2278,
      startDate: '2024-01-05',
      endDate: '2024-08-10',
      currentMatchday: 27,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2024-06-20T19:26:54Z',
  },
  {
    id: 2000,
    area: {
      id: 2267,
      name: 'World',
      countryCode: 'INT',
      ensignUrl: null,
    },
    name: 'FIFA World Cup',
    code: 'WC',
    emblemUrl: 'https://crests.football-data.org/qatar.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 1382,
      startDate: '2022-11-20',
      endDate: '2022-12-18',
      currentMatchday: 8,
      winner: {
        id: 762,
        name: 'Argentina',
        shortName: 'Argentina',
        tla: 'ARG',
        crestUrl: 'https://crests.football-data.org/762.png',
      },
    },
    numberOfAvailableSeasons: 22,
    lastUpdated: '2022-05-09T19:45:29Z',
  },
  {
    id: 2155,
    area: {
      id: 2267,
      name: 'World',
      countryCode: 'INT',
      ensignUrl: null,
    },
    name: 'WC Qualification CONCACAF',
    code: 'QCCF',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1651,
      startDate: '2024-03-18',
      endDate: '2024-03-26',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2021-11-11T10:39:10Z',
  },
  {
    id: 2153,
    area: {
      id: 2267,
      name: 'World',
      countryCode: 'INT',
      ensignUrl: null,
    },
    name: 'Summer Olympics',
    code: 'OLY',
    emblemUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1655,
      startDate: '2024-07-24',
      endDate: '2024-08-09',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2021-07-21T15:39:38Z',
  },
  {
    id: 2167,
    area: {
      id: 2267,
      name: 'World',
      countryCode: 'INT',
      ensignUrl: null,
    },
    name: "FIFA Women's World Cup",
    code: 'WCF',
    emblemUrl: 'https://crests.football-data.org/fwwc.svg',
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 1563,
      startDate: '2023-07-20',
      endDate: '2023-08-20',
      currentMatchday: 3,
      winner: {
        id: 6677,
        name: 'Spain',
        shortName: 'Spain',
        tla: 'ESP',
        crestUrl: 'https://crests.football-data.org/760.svg',
      },
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2023-04-05T11:47:08Z',
  },
];

export default competitions;
