const matches = [
  {
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    competition: {
      id: 2013,
      name: 'Campeonato Brasileiro Série A',
      code: 'BSA',
      type: 'LEAGUE',
      emblem: 'https://crests.football-data.org/bsa.png',
    },
    season: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    id: 493897,
    utcDate: '2024-07-07T19:00:00Z',
    status: 'TIMED',
    matchday: 15,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2024-06-23T15:20:40Z',
    homeTeam: {
      id: 3984,
      name: 'Fortaleza EC',
      shortName: 'Fortaleza',
      tla: 'FEC',
      crest: 'https://crests.football-data.org/3984.png',
    },
    awayTeam: {
      id: 1765,
      name: 'Fluminense FC',
      shortName: 'Fluminense',
      tla: 'FLU',
      crest: 'https://crests.football-data.org/1765.svg',
    },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
    },
    referees: [],
  },
  {
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    competition: {
      id: 2013,
      name: 'Campeonato Brasileiro Série A',
      code: 'BSA',
      type: 'LEAGUE',
      emblem: 'https://crests.football-data.org/bsa.png',
    },
    season: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    id: 493899,
    utcDate: '2024-07-07T19:00:00Z',
    status: 'TIMED',
    matchday: 15,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2024-05-31T15:21:18Z',
    homeTeam: {
      id: 4245,
      name: 'EC Juventude',
      shortName: 'Juventude',
      tla: 'JUV',
      crest: 'https://crests.football-data.org/4245_large.png',
    },
    awayTeam: {
      id: 1767,
      name: 'Grêmio FBPA',
      shortName: 'Grêmio',
      tla: 'FBP',
      crest: 'https://crests.football-data.org/1767.png',
    },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
    },
    referees: [],
  },
  {
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    competition: {
      id: 2013,
      name: 'Campeonato Brasileiro Série A',
      code: 'BSA',
      type: 'LEAGUE',
      emblem: 'https://crests.football-data.org/bsa.png',
    },
    season: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    id: 493895,
    utcDate: '2024-07-07T19:00:00Z',
    status: 'TIMED',
    matchday: 15,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2024-07-06T20:20:52Z',
    homeTeam: {
      id: 1771,
      name: 'Cruzeiro EC',
      shortName: 'Cruzeiro',
      tla: 'CRU',
      crest: 'https://crests.football-data.org/1771.png',
    },
    awayTeam: {
      id: 1779,
      name: 'SC Corinthians Paulista',
      shortName: 'Corinthians',
      tla: 'COR',
      crest: 'https://crests.football-data.org/1779.svg',
    },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
    },
    referees: [],
  },
  {
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    competition: {
      id: 2013,
      name: 'Campeonato Brasileiro Série A',
      code: 'BSA',
      type: 'LEAGUE',
      emblem: 'https://crests.football-data.org/bsa.png',
    },
    season: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    id: 493898,
    utcDate: '2024-07-07T21:00:00Z',
    status: 'TIMED',
    matchday: 15,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2024-07-01T15:21:31Z',
    homeTeam: {
      id: 6684,
      name: 'SC Internacional',
      shortName: 'Internacional',
      tla: 'SCI',
      crest: 'https://crests.football-data.org/6684.png',
    },
    awayTeam: {
      id: 1780,
      name: 'CR Vasco da Gama',
      shortName: 'Vasco da Gama',
      tla: 'VAS',
      crest: 'https://crests.football-data.org/1780.png',
    },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
    },
    referees: [],
  },
  {
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    competition: {
      id: 2013,
      name: 'Campeonato Brasileiro Série A',
      code: 'BSA',
      type: 'LEAGUE',
      emblem: 'https://crests.football-data.org/bsa.png',
    },
    season: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    id: 493902,
    utcDate: '2024-07-07T21:30:00Z',
    status: 'TIMED',
    matchday: 15,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2024-06-20T15:21:12Z',
    homeTeam: {
      id: 1782,
      name: 'EC Vitória',
      shortName: 'Vitória',
      tla: 'VIT',
      crest: 'https://crests.football-data.org/1782.png',
    },
    awayTeam: {
      id: 4243,
      name: 'Criciúma EC',
      shortName: 'Criciúma',
      tla: 'CRI',
      crest: 'https://crests.football-data.org/4243.png',
    },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
    },
    referees: [],
  },
  {
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    competition: {
      id: 2013,
      name: 'Campeonato Brasileiro Série A',
      code: 'BSA',
      type: 'LEAGUE',
      emblem: 'https://crests.football-data.org/bsa.png',
    },
    season: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    id: 493893,
    utcDate: '2024-07-07T21:30:00Z',
    status: 'TIMED',
    matchday: 15,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2024-05-31T15:21:18Z',
    homeTeam: {
      id: 3988,
      name: 'AC Goianiense',
      shortName: 'AC Goianiense',
      tla: 'ACG',
      crest: 'https://crests.football-data.org/3988.png',
    },
    awayTeam: {
      id: 1768,
      name: 'CA Paranaense',
      shortName: 'Paranaense',
      tla: 'CAP',
      crest: 'https://crests.football-data.org/1768.png',
    },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
    },
    referees: [],
  },
  {
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    competition: {
      id: 2013,
      name: 'Campeonato Brasileiro Série A',
      code: 'BSA',
      type: 'LEAGUE',
      emblem: 'https://crests.football-data.org/bsa.png',
    },
    season: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    id: 493900,
    utcDate: '2024-07-07T21:30:00Z',
    status: 'TIMED',
    matchday: 15,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2024-07-06T20:20:52Z',
    homeTeam: {
      id: 1769,
      name: 'SE Palmeiras',
      shortName: 'Palmeiras',
      tla: 'PAL',
      crest: 'https://crests.football-data.org/1769.png',
    },
    awayTeam: {
      id: 1777,
      name: 'EC Bahia',
      shortName: 'Bahia',
      tla: 'BAH',
      crest: 'https://crests.football-data.org/1777.png',
    },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
    },
    referees: [],
  },
  {
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    competition: {
      id: 2013,
      name: 'Campeonato Brasileiro Série A',
      code: 'BSA',
      type: 'LEAGUE',
      emblem: 'https://crests.football-data.org/bsa.png',
    },
    season: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 17,
      winner: null,
    },
    id: 493894,
    utcDate: '2024-07-07T23:30:00Z',
    status: 'TIMED',
    matchday: 15,
    stage: 'REGULAR_SEASON',
    group: null,
    lastUpdated: '2024-07-01T15:21:31Z',
    homeTeam: {
      id: 1770,
      name: 'Botafogo FR',
      shortName: 'Botafogo',
      tla: 'BOT',
      crest: 'https://crests.football-data.org/1770.png',
    },
    awayTeam: {
      id: 1766,
      name: 'CA Mineiro',
      shortName: 'Mineiro',
      tla: 'CAM',
      crest: 'https://crests.football-data.org/1766.png',
    },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
    },
    referees: [],
  },
];

export default matches;
